---
title: "Anomaly_flow_dataset"
output: html_document
---


# Load in helperfunctions and libraries

```{r}

source("../QC_Comparison_helper_function.R")

library(PeacoQC)
library(flowAI)
library(flowCut)
library(flowClean)
library(flowCore)
library(reshape2)
library(ggplot2)
library(ggpubr)

```


# Run preprocessing steps (necessary for flowAI to save files first)

```{r}
# Path to flow data 
files <- list.files("../../Data_flowRepository/", pattern = "flow", 
                    full.names = TRUE)

file <- files[1]

dir.create("flow_data")
dir.create("flow_data/preprocessed")

for (file in files){
    print(file)
    ff <- read.FCS(file, truncate_max_range = FALSE)
    
    markers <- colnames(ff)[c(1,4,7:10,12:19)]
        
    ff <- RemoveMargins(ff, channels = markers)
    ff <- compensate(ff, ff@description$SPILL)
    ff <- transform(ff, estimateLogicle(ff, colnames(ff@description$SPILL)))
    
    write.FCS(ff, paste0("flow_data/preprocessed/", basename(file)))
    
}

```



# Run quality control algorithms
```{r}

# Path to flow data 
files <- list.files("flow_data/preprocessed/", 
                    full.names = TRUE)

file <- files[1]

for (file in files[1:4]){
    print(file)
    ff <- read.FCS(file, truncate_max_range = FALSE)
    
    ff@description$`$FIL` <- file

    results_flowcut <- flowCut(ff,
                               Channels = which(colnames(ff) %in% markers),
                               Plot = "All",
                               FileID = sub(".fcs", "", basename(file)),
                               Verbose = F,
                               Directory = "flow_data/flowCut")

    write.FCS(results_flowcut$frame,
              filename = paste0("flow_data/flowCut/",
                                sub(".fcs","_QC.fcs", basename(file))))

    # Is necessary to make flowAI have the correct file ID
    tryout <- flowSet(ff)
    identifier(tryout[[1]]) <- basename(file)

    flowai <- tryCatch({flowai_full <- flow_auto_qc(tryout,
                                folder_results = "flow_data/FlowAI_full",
                                output = 1, ChExcludeFS = "Original_ID",
                                ChExcludeFM = "Original_ID")},
                             error = function(e){return(NA)})

    results_peacoqc <- PeacoQC(ff, 
                               channels = markers,
                               output_directory = 
                                   "flow_data/",
                               name_directory = "PeacoQC_Results",
                               display_cells = 2000,
                               save_fcs = T,
                               plot = T)
    
    dir.create("flow_data/flowClean")
    results_flowclean <- clean(fF = ff,
                               vectMarkers = which(colnames(ff) %in% markers),
                                filePrefixWithDir =
                                 paste0("flow_data/flowClean/",
                                        sub(".fcs", "", basename(file))),
                               ext = ".fcs",
                               diagnostic = T)


    write.FCS(results_flowclean,
              filename = paste0("flow_data/flowClean/",
                                sub(".fcs","_QC.fcs", basename(file))))

        

}


```


```{r}

files <- list.files("flow_data/preprocessed/")

file <- files[1]

for (file in files){
  
  print(file)
  
  ff <- read.FCS(file.path("flow_data/preprocessed/", basename(file)))
  
  set.seed(1)
  
  frame_cells <- ExtractQCCells(file, ff, directory = "flow_data")
  frame_cells.melted <- melt(frame_cells,
                             measure.vars = c("PeacoQC",
                                              "flowCut",
                                              "FlowAI",
                                              "flowClean"))
  sampled_cells <- sample(nrow(ff), 5000)
  
  
  frame <- data.frame("idc" = sampled_cells,
                      "time" = ff@exprs[sampled_cells, "Time"],
                      "cells_channel1" = ff@exprs[sampled_cells,12],
                      "cells_channel2" = ff@exprs[sampled_cells, 19])
  
  channels <- c(12,19)
  median_quantile_frame <-  CalculateMedianQuantile(ff, channels)
  subset_timeplot <- sort(sample(seq_len(nrow(ff)), 50000))
  
  h <- graphics::hist(flowCore::exprs(ff)[subset_timeplot, "Time"],
                      breaks=seq(min(flowCore::exprs(ff)[, "Time"]),
                                 max(flowCore::exprs(ff)[, "Time"]) +
                                   100, by=100),
                      plot=FALSE)
  
  h$events_1 <- sapply(h$mids, 
                       FUN = function(x){
                         which(abs(ff@exprs[,"Time"] - x) == 
                                 min(abs(ff@exprs[,"Time"]- x)))[1]})
  
  breaks <- sapply(h$breaks, 
                 FUN = function(x){
                   which(abs(ff@exprs[,"Time"] - x) ==
                           min(abs(ff@exprs[,"Time"] - x)))[1]})
  
  
  
  blocks_plot <- BuildBackgroundBlocks(h, breaks, file)
  
  scale_plot <- BuildManualScale(file)
  
  idcs <- findInterval(flowCore::exprs(ff)[subset_timeplot, "Time"], 
                       h$breaks)
  
  title_plot <- MakeTitle(file)
  
  p_time <- ggplot() + theme_bw() +
    blocks_plot + 
    scale_plot +
    geom_point(aes(x = h$events_1, y = h$counts), size = 0.2) +
    geom_line(aes(x = h$events_1, y = h$counts)) +
    scale_x_continuous(limits = c(0,max(breaks))) +
    ggtitle(title_plot) +
    theme(panel.grid=element_blank(),
          axis.line  = element_line(size = 0.5),
          axis.line.x = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.y = element_line(size = 0.5),
          axis.ticks.x = element_blank(),
          panel.border = element_blank()) +
    xlab("") + ylab("Nr of cells per second") +
    theme(plot.title=element_text(size=10, face = "bold")) 
  
  p_channel1 <- ggplot() +
    blocks_plot +
    scale_plot +
    geom_point(data = frame, aes(x = idc, y = cells_channel1), size = 0.4) +
    theme_bw() +
    theme(axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.line.y = element_line(size = 0.5)) +
    labs(y = colnames(ff)[channels[1]]) + 
    
    geom_line(data = median_quantile_frame,
              aes(x = median_quantile_frame[,1], y = median_quantile_frame[,2]),
              color = "red", size = 1)
  
  p_channel2 <- ggplot() +
    blocks_plot +
    scale_plot +
    geom_point(data = frame, aes(x = idc, y = cells_channel2), size = 0.4) +
    theme_bw() +
    theme(axis.title.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.line.y = element_line(size = 0.5)) +
    labs(y = colnames(ff)[channels[2]]) + 
    
    geom_line(data = median_quantile_frame,
              aes(x = median_quantile_frame[,1], y = median_quantile_frame[,6]),
              color = "red", size = 1)
  
  
  p_heatmap <- HeatmapQC(frame_cells.melted)
  
  legend_background <- get_legend(p_channel1)
  legend_p2 <- get_legend(p_heatmap)
  legend <- rbind(legend_background, legend_p2)
  legend_plot <- as_ggplot(legend)
  
  plot_without_legend <- ggarrange(p_time + theme(legend.position = "none"), 
                                   p_channel1
                                   + theme(legend.position = "none"), 
                                   p_channel2
                                   + theme(legend.position = "none"), 
                                   p_heatmap + theme(legend.position = "none"), 
                                   ncol = 1, 
                                   align = "v")
  
  final_plot <- ggarrange(plot_without_legend, legend_plot, 
                          nrow =1, widths = c(1,0.5))
  
  
  ggsave(file = paste0("flow_data/Comparison_", 
                       sub(".fcs", ".png", basename(file))), 
         width = 8,
         height = 7
  )
  
}

```



